name: Actions 😎
on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  activateAndThenReturnLicense:
    name: returnLicense 🎈
    runs-on: windows-2019

    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Return License
      - name: Return license
        uses: ./
        if: always()
